// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

const findTheDifference = (s, t) => {
  const sReduced = s
    .split("")
    .reduce(
      (accumulator, currentValue) => accumulator + currentValue.charCodeAt(0),
      0
    );
  console.log(sReduced);
  const tReduced = t
    .split("")
    .reduce(
      (accumulator, currentValue) => accumulator + currentValue.charCodeAt(0),
      0
    );
  return String.fromCharCode(tReduced - sReduced);
};
